apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
  namespace: java-dev
  labels:
    name: java-app-svc
spec:
  type: ClusterIP
  ports:
  - name: http 
    port: 80
    targetPort: 8080
  selector:
    app: java-app
